version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:stretch

    steps:
      - checkout

      - run:
          name: Print the latest commit
          command: git log -n 1
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v.*/
